export const SPOTIFY_AUTH_LOCAL = "spotifyAuth"
export const SPOTIFY_USER_LOCAL = "spotifyUser"
export const SPOTIFY_ALBUM_LOCAL = "spotifyAlbums"
export const USER_PREF_LOCAL = "userPref"
export const ANNIVERSIFY_DEVICE_TOKENS_SENT = "anniversifyTokensSent"
export const LASTFM_USER_DETAILS = "lastfmUserDetails"